#!/usr/bin/env python3
"""Write ./.env with fresh local-only secrets for the queue. Safe to re-run: it only adds what is missing.

    python3 docker/make_env.py

The queue replaces Supabase on this machine. Its keys are ordinary signed tokens that only
this local queue accepts; they are not Supabase credentials.
"""
import base64
import hashlib
import hmac
import json
import secrets
from pathlib import Path

ENV = Path(__file__).resolve().parent.parent / ".env"


def b64(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def token(secret: str, role: str) -> str:
    head = b64(json.dumps({"alg": "HS256", "typ": "JWT"}, separators=(",", ":")).encode())
    body = b64(json.dumps({"role": role, "iss": "local-queue", "exp": 4102444800}, separators=(",", ":")).encode())
    signature = hmac.new(secret.encode(), f"{head}.{body}".encode(), hashlib.sha256).digest()
    return f"{head}.{body}.{b64(signature)}"


def main() -> int:
    have = dict(line.split("=", 1) for line in ENV.read_text(encoding="utf-8").splitlines() if "=" in line and not line.startswith("#")) if ENV.exists() else {}
    jwt_secret = have.get("JWT_SECRET") or secrets.token_urlsafe(48)
    wanted = {
        "POSTGRES_PASSWORD": secrets.token_urlsafe(24),
        "AUTHENTICATOR_PASSWORD": secrets.token_urlsafe(24),
        "JWT_SECRET": jwt_secret,
        "SERVICE_KEY": token(jwt_secret, "service_role"),
        "AGENT_MCP_TOKEN": secrets.token_urlsafe(32),  # bearer token for the agent's MCP port
    }
    missing = {k: v for k, v in wanted.items() if k not in have}
    if not missing:
        print(f"{ENV} is complete; leaving it alone.")
        return 0
    header = [] if ENV.exists() else ["# Local queue secrets. Generated by docker/make_env.py. Do not commit."]
    with ENV.open("a", encoding="utf-8") as handle:
        handle.write("\n".join(header + [f"{k}={v}" for k, v in missing.items()]) + "\n")
    ENV.chmod(0o600)
    print(f"{ENV}: added {', '.join(missing)} (existing values kept)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
